[package]
name = "chud"
version = "0.1.0"
edition = "2021"

[lib]
name = "chud"
path = "src/lib.rs"

[dependencies]
libp2p = { version = "0.51.3", features = ["macros", "noise", "wasm-bindgen", "floodsub"] }
blake3 = "1.4.0"
serde_json = "1.0.96"
serde = { version = "1.0.164", features = ["derive"] }
captcha-rs = "0.2.10"
indexed_db_futures = "0.3.0"
web-sys = { version = "0.3.64", features = ["IdbFactory", "Window"] }
wasm-bindgen = "0.2.87"
serde-wasm-bindgen = "0.5.0"
async-std = { version = "1.12.0", features = ["attributes"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"