[package]
name = "chud-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.3.1"
chud = { path = "../../" }
wasm-logger = "0.2.0"
wasm-bindgen-futures = "0.4.37"
async-channel = "1.8.0"

[build-dependencies]
trunk = "0.16.0"